# Lab 1 — Strings and NumPy Arrays

In this lab, I first work on basic string manipulations in Python, and then I use `NumPy` to perform efficient numerical computations without relying on explicit Python loops whenever possible.

The notebook is written in a clear and compact style, as for a standard GitHub submission.

## Imports

In [1]:
import string
import math
import time
import numpy as np

# Part 1 — Strings

## Question 1

Using the `string` module, I retrieve the lowercase alphabet and generate the requested strings using slicing only.

In [2]:
alphabet = string.ascii_lowercase

s1 = alphabet[2::3]
s2 = alphabet[21::2]
s3 = alphabet[25:18:-2]

print(s1)
print(s2)
print(s3)

cfilorux
vxz
zxvt


## Question 2

I start from the string `" XHEC DataScience for Business "`, convert it to lowercase, remove leading and trailing spaces, and replace every `"e"` with `"E"`.

In [3]:
s = " XHEC DataScience for Business "
result = s.lower().strip().replace("e", "E")

print(result)

xhEc datasciEncE for businEss


## Question 3

I display the value of $\pi$ with 9 decimal digits using Python string formatting.

In [4]:
print(f"{math.pi:.9f}")

3.141592654


## Question 4

I count the number of occurrences of each character in the string `"HelLo WorLd!!"`, while treating uppercase and lowercase letters as identical.

In [5]:
s = "HelLo WorLd!!".lower()
counts = {}

for char in s:
    if char in counts:
        counts[char] += 1
    else:
        counts[char] = 1

print(counts)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1, '!': 2}


# Part 2 — Fast computations with NumPy

## Question 1 — Comparing floating-point numbers

I compute `0.1 + 100 - 100`, then compare the result to `0.1` using both `==` and `np.allclose`.

In [6]:
x = 0.1 + 100 - 100

print(x)
print(x == 0.1)
print(np.allclose(x, 0.1))

0.09999999999999432
False
True


Direct comparison with `==` may fail for floating-point numbers because of numerical approximation.  
`np.allclose` is more appropriate when comparing floating-point values.

## Question 2 — For-loop versus NumPy

### 2.1 Using a for-loop

In [7]:
squares_list = []

for i in range(1, 12):
    squares_list.append(i**2)

print(squares_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]


### 2.2 Using NumPy

In [8]:
squares_array = np.arange(1, 12) ** 2
print(squares_array)

[  1   4   9  16  25  36  49  64  81 100 121]


### 2.3 Comment

NumPy arrays should generally be preferred over Python loops for numerical computations because vectorized operations are faster, more concise, and easier to read.

## Question 3 — NumPy built-in functions

### 3.1 Array from 2 to 14 with step 3

In [9]:
a = np.arange(2, 15, 3)
print(a)

[ 2  5  8 11 14]


### 3.2 15 equally spaced values from 0 to 1

In [10]:
b = np.linspace(0, 1, 15)
print(b)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


## Question 4 — Vectorizing a product

I approximate the infinite product

\[
2\prod_{k=1}^{\infty}\frac{4k^2}{4k^2 - 1}
\]

by replacing $\infty$ with a large integer $n$.

### 4.1 Version using a for-loop

In [11]:
n = 10000
prod_value = 1.0

for k in range(1, n + 1):
    prod_value *= (4 * k**2) / (4 * k**2 - 1)

result_loop = 2 * prod_value
print(result_loop)

3.1415141186819566


### 4.2 Vectorized NumPy version

In [12]:
k = np.arange(1, n + 1)
result_numpy = 2 * np.prod((4 * k**2) / (4 * k**2 - 1))

print(result_numpy)

3.1415141186819566


### 4.3 Timing both versions

In [13]:
start = time.time()

prod_value = 1.0
for k in range(1, n + 1):
    prod_value *= (4 * k**2) / (4 * k**2 - 1)
result_loop = 2 * prod_value

loop_time = time.time() - start

start = time.time()

k = np.arange(1, n + 1)
result_numpy = 2 * np.prod((4 * k**2) / (4 * k**2 - 1))

numpy_time = time.time() - start

print(f"Loop result  : {result_loop:.10f}")
print(f"NumPy result : {result_numpy:.10f}")
print(f"Loop time    : {loop_time:.6f} s")
print(f"NumPy time   : {numpy_time:.6f} s")
print(np.allclose(result_loop, result_numpy))

Loop result  : 3.1415141187
NumPy result : 3.1415141187
Loop time    : 0.002079 s
NumPy time   : 0.002575 s
True


### 4.4 `%timeit`

In a Jupyter notebook, `%timeit` is more reliable than `time.time()` because it repeats the computation several times and gives a more stable estimate.

In [14]:
%timeit 2 * np.prod((4 * np.arange(1, n + 1)**2) / (4 * np.arange(1, n + 1)**2 - 1))

48.9 μs ± 1.68 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Question 5 — Row and column vectors

### 5.1 Dot product

In [15]:
a = np.arange(5)
b = np.ones(5)

print(np.dot(a, b))

10.0


### 5.2 Shape of `np.arange(5)`

In [16]:
print(a.shape)

(5,)


### 5.3 Number of dimensions

In [17]:
print(a.ndim)

1


### 5.4 Shape of its transpose

In [18]:
print(a.T.shape)

(5,)


### 5.5 Comment

A 1D NumPy array is neither a row vector nor a column vector in the matrix sense.  
Transposing a 1D array has no effect.

## Question 6 — Array shapes

### 6.1 `reshape`

In [19]:
M = np.arange(12).reshape(2, 6)
print(M)
print(M.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


`reshape(2, 6)` reorganizes the 12 values into a matrix with 2 rows and 6 columns.

### 6.2 Slicing with `M[:, ::3]`

In [20]:
print(M[:, ::3])

[[0 3]
 [6 9]]


This selects all rows and one column out of every three.

### 6.3 Broadcasting

In [21]:
result = np.arange(3) * np.arange(4)[:, np.newaxis]
print(result)
print(result.shape)

[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]]
(4, 3)


This uses broadcasting to produce a matrix of shape `(4, 3)`.

## Question 7 — Array manipulation

### 7.1 Random matrix in $[-1, 1]$

In [22]:
rng = np.random.default_rng(42)
M = rng.uniform(-1, 1, size=(5, 10))
print(M)
print(M.shape)

[[ 0.5479121  -0.12224312  0.71719584  0.39473606 -0.8116453   0.9512447
   0.5222794   0.57212861 -0.74377273 -0.09922812]
 [-0.25840395  0.85352998  0.28773024  0.64552323 -0.1131716  -0.54552256
   0.10916957 -0.87236549  0.65526234  0.2633288 ]
 [ 0.51617548 -0.29094806  0.94139605  0.78624224  0.55676699 -0.61072258
  -0.06655799 -0.91239247 -0.69142102  0.36609791]
 [ 0.48952431  0.93501946 -0.34834928 -0.25908059 -0.06088838 -0.62105728
  -0.74015699 -0.04859015 -0.5461813   0.33962799]
 [-0.12569616  0.66535639  0.4005302  -0.37526672  0.6645196   0.60952871
  -0.22504324 -0.42334379  0.36499101 -0.72049503]]
(5, 10)


### 7.2 Modify even columns

I subtract twice the following odd column from each even column.

In [23]:
M[:, ::2] -= 2 * M[:, 1::2]
print(M)

[[ 0.79239834 -0.12224312 -0.07227628  0.39473606 -2.71413471  0.9512447
  -0.62197782  0.57212861 -0.54531649 -0.09922812]
 [-1.96546391  0.85352998 -1.00331621  0.64552323  0.97787351 -0.54552256
   1.85390055 -0.87236549  0.12860475  0.2633288 ]
 [ 1.09807161 -0.29094806 -0.63108844  0.78624224  1.77821216 -0.61072258
   1.75822694 -0.91239247 -1.42361683  0.36609791]
 [-1.38051462  0.93501946  0.16981189 -0.25908059  1.18122619 -0.62105728
  -0.64297669 -0.04859015 -1.22543728  0.33962799]
 [-1.45640895  0.66535639  1.15106364 -0.37526672 -0.55453783  0.60952871
   0.62164434 -0.42334379  1.80598107 -0.72049503]]


## Question 8 — More array manipulation

### 8.1 Replace negative values by 0

In [24]:
M[M < 0] = 0
print(M)

[[0.79239834 0.         0.         0.39473606 0.         0.9512447
  0.         0.57212861 0.         0.        ]
 [0.         0.85352998 0.         0.64552323 0.97787351 0.
  1.85390055 0.         0.12860475 0.2633288 ]
 [1.09807161 0.         0.         0.78624224 1.77821216 0.
  1.75822694 0.         0.         0.36609791]
 [0.         0.93501946 0.16981189 0.         1.18122619 0.
  0.         0.         0.         0.33962799]
 [0.         0.66535639 1.15106364 0.         0.         0.60952871
  0.62164434 0.         1.80598107 0.        ]]


### 8.2 Mean of each row

In [25]:
row_means = M.mean(axis=1)
print(row_means)

[0.27105077 0.47227608 0.57868509 0.26256855 0.48535742]


### 8.3 Subtract the row mean from each row

In [26]:
M -= row_means[:, np.newaxis]
print(M)

[[ 0.52134757 -0.27105077 -0.27105077  0.12368529 -0.27105077  0.68019393
  -0.27105077  0.30107784 -0.27105077 -0.27105077]
 [-0.47227608  0.3812539  -0.47227608  0.17324715  0.50559743 -0.47227608
   1.38162447 -0.47227608 -0.34367133 -0.20894728]
 [ 0.51938652 -0.57868509 -0.57868509  0.20755716  1.19952708 -0.57868509
   1.17954186 -0.57868509 -0.57868509 -0.21258718]
 [-0.26256855  0.67245091 -0.09275666 -0.26256855  0.91865763 -0.26256855
  -0.26256855 -0.26256855 -0.26256855  0.07705944]
 [-0.48535742  0.17999898  0.66570622 -0.48535742 -0.48535742  0.1241713
   0.13628693 -0.48535742  1.32062366 -0.48535742]]


## Question 9 — Linear algebra

### 9.1 Random matrix

In [27]:
M = rng.uniform(-1, 1, size=(5, 10))

### 9.2 Define $G = M^T M$ and study its properties

In [28]:
G = M.T @ M
print(G.shape)
print(np.allclose(G, G.T))

(10, 10)
True


`G` is symmetric because it is of the form $M^T M$.

### Eigenvalues

In [29]:
eigvals = np.linalg.eigvalsh(G)
print(eigvals)

[-9.07972381e-16 -6.54502386e-17  1.88520177e-16  4.43642701e-16
  6.88546981e-16  2.11025534e-01  2.03012457e+00  2.90282855e+00
  3.62153011e+00  5.26557282e+00]


### Positive semi-definiteness

In [30]:
print(np.all(eigvals >= -1e-12))

True


This confirms numerically that $G$ is positive semi-definite.

### Strict positivity of eigenvalues

In [31]:
print(np.all(eigvals > 1e-12))

False


This is generally `False` here, because `M` has shape `(5, 10)`, so the rank of $G$ is at most 5. Therefore, $G$ cannot have 10 strictly positive eigenvalues.

### 9.3 Rank

In [32]:
rank_G = np.linalg.matrix_rank(G)
print(rank_G)

5


### 9.4 Euclidean norm

In [33]:
fro_norm = np.linalg.norm(G)
print(fro_norm)

7.309862425798061


### 9.5 Operator norm

In [34]:
op_norm = np.linalg.norm(G, 2)
print(op_norm)

5.265572824622327


### 9.6 Standard deviation of each column

In [35]:
std_cols = G.std(axis=0)
print(std_cols)

[0.55956796 0.62820213 0.62434531 0.71976253 0.99099408 0.7142867
 0.31139326 0.51255663 0.84624824 0.85797237]


# Conclusion

This lab was a good introduction to both standard Python string manipulation and efficient numerical computing with `NumPy`.

The main concepts I practiced in this notebook were:
- string slicing and string methods,
- dictionary-based counting,
- floating-point precision issues,
- vectorization with `NumPy`,
- array shapes and broadcasting,
- and basic linear algebra operations.